
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 app/
    - name: Lint with mypy
      run: |
        mypy app/
    - name: Lint with black
      run: |
        black --diff --check --line-length 79 app/
    - name: Lint with isort
      run: |
        isort --check-only -- diff app/
    - name: Lint with pytest
      run: |
        pytest tests
